config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('website.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^meeting/', include('website.meeting.urls', namespace='meeting')),
    url(r'^presentation/', include('website.presentation.urls', namespace='presentation')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

website/meeting/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^request/$',
        view=views.ApplicatorCreate.as_view(),
        name='request'
    ),

]

website/presentation/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    # url(
    #     regex=r'^$',
    #     view=views.HistoryView,
    #     name='search'
    # ),
    url(
        regex=r'^history/$',
        view=views.HistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^search/$',
        view=views.Search.as_view(),
        name='search'
    ),

]

website/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

website/meeting/models.py
from __future__ import unicode_literals


from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _



# Create your models here.
@python_2_unicode_compatible
class Applicator(models.Model):
    name = models.CharField(max_length=200,verbose_name=_('Name'))
    lastname = models.CharField(max_length=200,verbose_name=_('Lastname'))
    company_name = models.CharField(max_length=200,verbose_name=_('Company'))
    phone = models.CharField(max_length=200,verbose_name=_('Phone'))
    address = models.CharField(max_length=400,verbose_name=_('Address'),blank=True)
    city = models.CharField(max_length=50,verbose_name=_('City'),blank=True)
    email = models.EmailField(blank=False,verbose_name=_('Email'))
    website = models.URLField(blank=True,verbose_name=_('Website'))
    rank = models.CharField(max_length=200,verbose_name=_('Rank'))
    request_date = models.DateTimeField()
    set_date = models.DateTimeField(blank=True,null=True)
    date_has_been_set = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Applicator")
        verbose_name_plural = _("Applicators")
        ordering = ("request_date","company_name",)

    def __str__(self):
        return '{0} - {1} -> {2}'.format(self.company_name,self.phone,self.request_date)

website/presentation/models.py
from __future__ import unicode_literals, absolute_import

from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import JSONField

from config.settings import common


# Create your models here.
@python_2_unicode_compatible
class UserRequest(models.Model):
    action_time = models.DateTimeField(
        _('action time'),
        default=timezone.now,
        editable=False,
    )
    user = models.ForeignKey(
        common.AUTH_USER_MODEL,
        models.CASCADE,
        verbose_name=_('user'),
    )
    req_national_id = models.TextField(_('national id'), blank=False, null=False)
    resp_cheque = JSONField(_('response_cheque'), blank=True, null=True)
    resp_loans = JSONField(_('response_loans'), blank=True , null=True)


    def __str__(self):
        return self.req_national_id + str(self.user)

    class Meta:
        ordering = ['action_time']

website/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import  ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    num_of_requests = models.PositiveIntegerField(_('Number of Requests'),default=0)
    num_of_requests_used = models.PositiveIntegerField(_('Number of Requests Made'),default=0)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_username(self):
        return self.username

    def get_full_name(self):
        return '{} {}'.format(self.first_name,self.last_name)

website/meeting/forms.py
from django.forms import ModelForm
from django.contrib.admin import widgets

from .models import Applicator


class ApplicatorForm(ModelForm):
    class Meta:
        model = Applicator
        exclude = ('set_date','date_has_been_set',)
        widgets = {
            'request_date' : widgets.AdminSplitDateTime(),
        }

website/presentation/forms.py
from django import forms


class SearchForm(forms.Form):
    query_n_id = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),label='شماره ملی',required=True,
                                 max_length=10,min_length=10,error_messages={'query_n_id':'کد ملی یک عدد ده رقمی است.'})

    def clean_query_n_id(self):
        query_n_id = self.cleaned_data['query_n_id']
        if not query_n_id.isdigit():
            raise forms.ValidationError('Mix of Numbers and digits is not allowed')
        return query_n_id

website/meeting/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import ApplicatorForm

# Create your views here.


class ApplicatorCreate(FormView):
    form_class = ApplicatorForm
    template_name = 'meeting/request_form.html'


    def post(self, request, *args, **kwargs):
        form = ApplicatorForm(request.POST)

website/presentation/views.py
from datetime import datetime

from django.template.loader import render_to_string
from django.views.generic import ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import JsonResponse


from .models import UserRequest
from .forms import SearchForm

from suds import Client

# Create your views here.


event_text = '<br />چک برگشتی : {0}<br />مبلغ : {1}<br />صادره : {2}<br />تاریخ چک : {3}<br />تاریخ برگشت چک : {4}<br />'
event_text_loan = '<br />مقدار کل بدهی : {0}<br />مقدار سود : {1}<br />مقدار سررسید : {2}<br />مقدار معوق : {3}' \
                  '<br />مقدار مشکوک : {4}<br /><br />شعبه : {5}<br />'


class HistoryView(LoginRequiredMixin, ListView):
    template_name = 'presentation/history.html'
    model = UserRequest
    context_object_name = 'history'

    def get_queryset(self):
        return UserRequest.objects.filter(user=self.request.user)


class Search(LoginRequiredMixin, View):
    """ Call the class that handles Inquiry Service Call """

    def get(self, request):
        form = SearchForm()
        params = dict()
        params["search"] = form
        return render(request, 'presentation/search.html', params)

    def post(self, request):
        form = SearchForm(request.POST)
        user = request.user
        if form.is_valid() and user.num_of_requests_used < user.num_of_requests:
            data_getter = GetDataFromInquiry()
            query = form.cleaned_data['query_n_id']
            results = dict()
            try:
                req_obj = UserRequest.objects.filter(req_national_id=query)[0]
                print(req_obj)
                if req_obj:
                    if req_obj.resp_cheque:
                        results['check'] = req_obj.resp_cheque
                    else:
                        results['check'] = None
                    if req_obj.resp_loans:
                        results['loan'] = req_obj.resp_loans
                    else:
                        results['loan'] = None
            except IndexError:
                results = data_getter.getdata(query)

            context = dict()
            if results['check']:
                context['check'] = True
            if results['loan']:
                context['loan'] = True
            user.num_of_requests_used += 1
            user.save()

            databse_obj = UserRequest(user=request.user, req_national_id=query, resp_cheque=results['check'],
                                      resp_loans=results['loan'])
            return_str = render_to_string('presentation/partials/_search_results.html', {'result_types': context})
            databse_obj.save()
            return JsonResponse({'page': return_str, 'data': results,})
        else:
            return JsonResponse({'error': form.errors})


class GetDataFromInquiry:
    def __init__(self, url='http://172.16.5.200:8082/InquiryService.svc?wsdl'):

        self.__URL = url
        self.__CLIENT = Client(self.__URL)
        self.__TRANSLATOR = str.maketrans(u'1234567890', u'۱۲۳۴۵۶۷۸۹۰')

    def format_date(self, date):
        return '{0}/{1}/{2}'.format(date[:4], date[4:6], date[6:])

    def getdata(self, national_id):
        results = dict()
        results['check'] = self.getcheckinfo(national_id)
        results['loan'] = self.getloaninfo(national_id)
        return results

    def getloaninfo(self, national_id):
        try:
            result = self.__CLIENT.service.GetOnlineFullFacilityInfo(national_id)
            json_obj_temp = dict()
            json_obj_temp['title'] = {}
            json_obj_temp['events'] = []
            if result and bool(result['IsErrorHappened']) is False:
                if int(result['TotalAmOriginal']) == 0:
                    json_obj_temp = None
                elif result['TotalAmOriginal'] > 0:
                    json_obj_temp['title'] = {
                        'text': {'headline': '<strong>{0} {1}</strong>'.format(result['Name'], result['LName']),
                                 'text': '<p> تعداد وام های جاری :{0} </p><p>مجموع مبالغ : {1} مقدار اصل تسهیلات {2} و سود {3}</p>'.format(
                                     str(len(result['FacilityInformationItems'][0])).translate(self.__TRANSLATOR),
                                     str(result['TotalAmTashilat']).translate(self.__TRANSLATOR),
                                     str(result['TotalAmOriginal']).translate(self.__TRANSLATOR),
                                     str(result['TotalAmBedehi']).translate(self.__TRANSLATOR)
                                 )}}
                    if len(result['FacilityInformationItems']) > 0:
                        for item in result['FacilityInformationItems'][0]:
                            print(item)
                            event_date = datetime.now()
                            json_obj_temp['events'].append(
                                {'text': dict(
                                    headline='{0} مقدار تسهیلات'.format(
                                        str(item['AmOriginal']).translate(self.__TRANSLATOR)),
                                    text=event_text_loan.format(
                                        str(item['AmBedehiKol']).translate(self.__TRANSLATOR),
                                        str(item['AmBenefit']).translate(self.__TRANSLATOR),
                                        str(item['AmSarResid']).translate(self.__TRANSLATOR),
                                        str(item['AmMoavagh']).translate(self.__TRANSLATOR),
                                        str(item['AmMashkuk']).translate(self.__TRANSLATOR),
                                        str(item['BnkShb']).translate(self.__TRANSLATOR),
                                    )),
                                    'start_date': {'month': event_date.month, 'day': event_date.day,
                                                   'year': event_date.year}
                                })

            else:
                json_obj_temp = None
        except Exception:
            return None

        return json_obj_temp

    def getcheckinfo(self, national_id):
        try:
            result = self.__CLIENT.service.GetOnlineFullCheckInfo(national_id)
            json_obj_temp = dict()
            json_obj_temp['title'] = {}
            json_obj_temp['events'] = []
            if result and bool(result['IsErrorHappened']) is False:
                if int(result['CheckCount']) == 0:
                    json_obj_temp = None
                elif result['CheckCount'] > 0:
                    json_obj_temp['title'] = {'text': {'headline': '<strong>{0}</strong>'.format(result['Name']),
                                                       'text': '<p>{0}چک برگشتی </p><br /><p>{1}کل بدهی</p>'.format(
                                                           str(result['CheckCount']).translate(self.__TRANSLATOR),
                                                           str(result['CheckAmountSum']).translate(self.__TRANSLATOR))}}
                    if len(result['CheckInformationItems']) > 0:
                        for item in result['CheckInformationItems'][0]:
                            print(item)
                            event_date = datetime.strptime(str(item['ReturnedDate']), '%Y-%m-%d %X')
                            json_obj_temp['events'].append(
                                {'text': dict(
                                    headline='{0} چک به شماره'.format(item['NOCHQ'].translate(self.__TRANSLATOR)),
                                    text=event_text.format(
                                        item['IDCHQ'].translate(self.__TRANSLATOR),
                                        item['AMCHQ'],
                                        item['DESC'],
                                        self.format_date(item['DTCHQ'].translate(self.__TRANSLATOR)),
                                        self.format_date(item['BCKDTCHQ'].translate(self.__TRANSLATOR))
                                    )),
                                    'start_date': {'month': event_date.month, 'day': event_date.day,
                                                   'year': event_date.year}
                                })
            else:
                json_obj_temp = None
        except Exception:
            return None

        return json_obj_temp

website/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from website.presentation.models import UserRequest


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name','first_name','last_name',]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

website/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="fa" class="no-js" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}website{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
        <!-- Your stuff: Third-party css libraries go here -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body data-spy="scroll" data-target=".navbar-collapse" data-offset="50" {% ifequal LANGUAGE_CODE 'fa' %}class="persian-content"{% endifequal %}>

<nav class="" style="background-color: #009DDC;">
    <div class="pull-xs-left">
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
            &#9776;
        </button>

    </div>
    <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
        <img class="navbar-brand pull-xs-right" style="width : 30px;" src="{% static 'images/icbs_logo.png' %}" />
        <a class="navbar-brand pull-xs-right" href="{% url 'home' %}">{% trans "Company Name" %}</a>
        <ul class="nav navbar-nav pull-xs-right">
            <li class="nav-item "><a class="nav-link" href="#slide-5">{% trans "Contact Us" %}</a></li>
            <li class="nav-item "><a class="nav-link" href="#slide-3">{% trans "Our Customers" %}</a></li>
            <li class="nav-item "><a class="nav-link" href="#slide-2">{% trans "About Us" %}</a></li>
            <li class="nav-item "><a class="nav-link" href="#slide-home">{% trans "Home" %}</a></li>
        </ul>
        <ul class="nav navbar-nav pull-xs-left">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'meeting:request'%}"><i class="fa fa-book"></i> {% trans "Request Meeting" %}</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:detail' request.user.username  %}"><i class="fa fa-gear"></i>  {% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> {% trans "Sign out" %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}"><i class="fa fa-sign-in"></i> {% trans "Sign In" %}</a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav>


{% block head %}


{% endblock %}

{% if messages %}
    <div class="container messages">

        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </div>
        {% endfor %}

    </div>
{% endif %}

<div class="container-fluid body-section">

    {% block content %}

    {% endblock content %}
    <div class="loader loader--style5" title="Please Wait..." style="display: none;">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="24px" height="30px" viewBox="0 0 24 30" style="enable-background:new 0 0 50 50;" xml:space="preserve">
    <rect x="0" y="0" width="4" height="10" fill="#333">
      <animateTransform attributeType="xml"
        attributeName="transform" type="translate"
        values="0 0; 0 20; 0 0"
        begin="0" dur="0.6s" repeatCount="indefinite" />
    </rect>
    <rect x="10" y="0" width="4" height="10" fill="#333">
      <animateTransform attributeType="xml"
        attributeName="transform" type="translate"
        values="0 0; 0 20; 0 0"
        begin="0.2s" dur="0.6s" repeatCount="indefinite" />
    </rect>
    <rect x="20" y="0" width="4" height="10" fill="#333">
      <animateTransform attributeType="xml"
        attributeName="transform" type="translate"
        values="0 0; 0 20; 0 0"
        begin="0.4s" dur="0.6s" repeatCount="indefinite" />
    </rect>
  </svg>
    </div>

</div> <!-- /container -->


{% block modal %}

{% endblock modal %}


<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Latest JQuery -->
    <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
    <!-- Tether - a requirement for Bootstrap tooltips -->
    <script src="{% static 'js/tether.min.js'%}"></script>

    <!-- Latest compiled and minified JavaScript -->


    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="{% static 'js/what-input.js' %}"></script>
    <script src="{% static 'js/foundation.min.js' %}"></script>
    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
{% block extrajs %}{% endblock %}

</body>
</html>